spring:
  application:
    name: springboot3-mail
  mail:
    # 你的邮箱，发邮件的邮箱
    username: 123456789@163.com
    # 你的授权码，邮箱里面设置->POP3/SMTP/IMAP
    password: --------------
    host: smtp.163.com

# Logger Config
logging:
  level:
    com.hexadecimal: debug
